version: '3.8'

services:
  mongo:
    image: mongo:4
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  redis:
    container_name: redis
    image: redis
    environment:
      - ALOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
volumes:
  mongo-data:
