spring:
  application:
    name: basket-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: basket-service
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
      authentication-database: ${MONGO_AUTH_DB}
    redis:
      host: localhost
      port: 6379

  cache:
    redis:
      time-to-live: 60000

basket:
  client:
    platzi: https://api.escuelajs.co/api/v1